### ISSUE TITLE
Esquema de la base de datos

### ISSUE THREAD

**Issue by islobell** [islobell/CAIN#1]
Este es el esquema que he pensado para gestionar la información de los archivos de música. Esta basado en el esquema de MusicBrainz:

![musicdb](https://cloud.githubusercontent.com/assets/9166208/5817246/23d7b17c-a0aa-11e4-9b34-d8ce9ae63743.png)

Básicamente, la información de una canción se aglutina en torno a un álbum.
¿Qué te parece?

**Comment by aoltra** [comment]
Te comento algunas cosas:

> - Creo que deberíamos tener en cuenta la posibilidad de que varios artistas sean los interpretes de una canción. Por ejemplo una colaboración de esas que están ahora muy de moda ;)

> - ¿Qué es exactamente *TextReps*? ¿Hace referencia a la letra?. ¿Si es así no tendría que estar en el track? Podría ser interesante tener una tabla de idioma ES-ES, EN-US...

> - Hay que darle alguna vuelta a la posibilidad de relacionar canciones con versiones...*MusicBrainz* usa una tabla denominada *work* para indicar la grabación original

> - A lo que si que hay que darle vueltas es a las etiquetas, puesto que son el motor del posterior motor de búsqueda. Hay que implementarlas de alguna otra manera que nos permita posteriormente realizar consultas eficientes. Te dejo algunos enlaces

[how-do-you-recommend-implementing-tags-or-tagging](http://stackoverflow.com/questions/20856/how-do-you-recommend-implementing-tags-or-tagging)
[tags-database-schemas](http://tagging.pui.ch/post/37027745720/tags-database-schemas)

> - No tengo muy claro que necesitemos almacenar en la BD el *Cover*? ¿Hay alguna forma de obtenerlo de manera rápida del MP3? Sí, ya se que ene esa caso tendría que estar para cada canción del albúm y no una única vez, pero también es verdad que únicamente la vamos a utilizar como visualización. 

> - En el *track* haría falta algo que almacenase la huella digital

**Comment by islobell** [comment]
Paso a comentar cada uno de los puntos:

**Creo que deberíamos tener en cuenta la posibilidad de que varios artistas sean los interpretes de una canción**

Esto esta resuelto con la tabla **TrackArtists** ya que representa una relación 1..n entre las pistas y los artistas.

**¿Qué es exactamente TextReps? ¿Hace referencia a la letra? ¿Si es así no tendría que estar en el track?...**

Creo que es información irrelevante para nuestros propósitos y, por lo tanto, queda descartada.

**Hay que darle alguna vuelta a la posibilidad de relacionar canciones con versiones... MusicBrainz usa una tabla denominada *work* para indicar la grabación original**

Jejeje... estaría bien, pero creo que de momento si conseguimos obtener información de los archivos de audio ya me daría por satisfecho.

**A lo que si que hay que darle vueltas es a las etiquetas, puesto que son el motor del posterior motor de búsqueda. Hay que implementarlas de alguna otra manera que nos permita posteriormente realizar consultas eficientes...**

Por lo que he visto en los enlaces, los esquemas de la base de datos para tags están pensados para que los tags se almacenen en una tabla aparte. Luego para obtener la información se realizan complicadas consultas uniendo tablas.

En nuestro caso, los tags a almacenar son conocidos de antemano y por tanto no veo mayor inconveniente en que estén en la misma tabla que las canciones. Además, al no separarlos, las consultas son más sencillas y se obtienen los resultados más rápidamente.

Al menos para la información que vamos a almacenar, creo que es lo más adecuado. Sin embargo, si hay algo que se me escapa, dímelo.

**No tengo muy claro que necesitemos almacenar en la BD el Cover? ¿Hay alguna forma de obtenerlo de manera rápida del MP3? Sí, ya se que ene esa caso tendría que estar para cada canción del albúm y no una única vez, pero también es verdad que únicamente la vamos a utilizar como visualización.**

Se puede almacenar en el archivo de audio, pero eso aumentaría considerablemente su tamaño.
No sé cómo de rápido sería extraer el cover pues habría que echar mano de alguna librería de terceros. Creo que almacenarlo en la base de datos es una muy buena solución. ¿Qué inconvenientes ves?

**En el track haría falta algo que almacenase la huella digital**

Yo había pensado almacenar la huella digital de cada fichero de audio en el archivo .idx que crearemos en cada carpeta escaneada. Cada vez que se escanee de nuevo la carpeta comparará la huella digital generada de cada fichero de audio con la lista de huellas digitales de ese fichero. Si existe, se obviará el fichero; en caso contrario, se iniciará la búsqueda de información.

**Comment by aoltra** [comment]
**TrackArtist** :+1: , tal vez faltaría añadir pues una descripción y no tengo muy clara la diferencia entre el ID y el *ArtistID*

**Comment by islobell** [comment]
En la tabla **TrackArtists**, ¿a qué haría referencia la descripción?

En la tabla **TrackArtists**,  los campos *TrackID* y *ArtistID* son claves foráneas que hacen referencia al ID (claves primarias) de otras tablas.  El ID es el identificador autonumérico que asigna la base de datos al añadir un nuevo registro en la tabla, mientras que los campos *ArtistId*, *AlbumId*, etc... son identificadores (32 caracteres) de MusicBrainz y los guardo por si (a posteriori) hay que buscar información en su base de datos.

**Comment by aoltra** [comment]
La descripción sería una campo para poder especificar en caso de ambiguedades. Por ejemplo si hay más de un artista que se llame *Queen*, poder dar una pequeña descripción (estará vacía en la gran mayoría de los casos). Será útil a la hora de explotar la base de datos posteriormente.

Te refieres a algo así como el *ipi* o el *isni*, ¿verdad? Me parece perfecto. Lo que no sé es si en la tabla de relación entre el *Track* y el *Artista* deberíamos utilizar el *ID* o el *ArtistID*. Imagino que haces referencia al ID de la tabla *Artist* pero con el nombre *ArtistID*, Si le pudieras cambiar el nombre al campo *ArtistID* de la tabla *Artist* quedaría mejor.

**Comment by islobell** [comment]
El campo descripción me parece bien. 

En realidad es el **MBID** (https://musicbrainz.org/doc/MusicBrainz_Identifier). ¿Prefieres que cambie el nombre de todos los identificadores de MusicBrainz por MBID? Así nos quedaría más claro. Por ejemplo, el campo *ArtistId* de la tabla **Artists** pasaría a llamarse *MBID*, el campo *AlbumId* de la tabla **Albums** pasaría a llamarse *MBID*, etc...

¿Mejor así?

**Comment by aoltra** [comment]
OK. :+1:
